Update install

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -102,9 +102,27 @@ phpversion=$(ynh_app_setting_get --app=$app --key=phpversion)
 #=================================================
 ynh_script_progression --message="Installing with Composer..." --weight=30
 
-ynh_install_composer --phpversion=$phpversion --workdir=$final_path --install_args="--prefer-source --no-dev"
+#ynh_install_composer --phpversion=$phpversion --workdir=$final_path --install_args="--prefer-source --no-dev"
+
 
 pushd "$final_path"
+
+	EXPECTED_SIGNATURE=$(wget https://composer.github.io/installer.sig -O - -q)
+	curl -s https://getcomposer.org/installer > composer-setup.php
+	ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+
+	if [ "$EXPECTED_SIGNATURE" = "$ACTUAL_SIGNATURE" ]
+	then
+	   php composer-setup.php --quiet
+	   RESULT=$?
+	   rm composer-setup.php
+	else
+	   >&2 echo 'ERROR: Invalid composer installer signature'
+	   rm composer-setup.php
+	   exit 1
+	fi
+
+
 	php$phpversion ./composer.phar install --no-dev
 	yarn install
 	yarn buildall
